# fly.toml app configuration file generated for book-portal-mujtaba on 2023-08-09T16:26:48+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "book-portal-mujtaba"
primary_region = "sin"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
